=== Alexcr0103/EjerciciosLMSGI2023-24/Practicas/examen1.dtd
<!ELEMENT juicio (abogado | delitos | lugar)*> <!-- Cardinalidad 0, muchos-->
<!ENTITY % atributoNombre "nombre (Chicago | California | Texas) 'New York'"> <!-- Entidad parámetro-->
<!ELEMENT abogado EMPTY> <!-- Elemento vacio -->
<!ATTLIST abogado nombre CDATA #REQUIRED
                  defiende CDATA #IMPLIED
                  acusa ID #REQUIRED
                  especialidad CDATA #FIXED "civil"> <!-- Uso de required, implied y fixed--> <!-- Uso de ID-->
<!ELEMENT delitos ((multa | carcel), antedecentes?)> <!-- Cardinalidad puede o no estar--> <!-- Secuencia de elementos con optativa-->
<!ATTLIST delitos tipo CDATA #REQUIRED               
                  acusado IDREF #IMPLIED> <!-- Uso de IDREF-->
<!ELEMENT multa (#PCDATA | antedecentes)*> <!-- Tipo mixto-->
<!ELEMENT antedecentes (#PCDATA)>
<!ELEMENT carcel (#PCDATA)>
<!ATTLIST carcel %atributoNombre;> <!-- Uso de entidad parámetro-->
<!ELEMENT antecedentes (#PCDATA)>
<!ELEMENT lugar (ciudad+, personasCitadas, juzgado)> <!-- Cardinalidad 1 o mas-->
<!ELEMENT ciudad (#PCDATA)>
<!ATTLIST ciudad %atributoNombre;> <!-- Uso de entidad parámetro-->
<!ELEMENT personasCitadas (#PCDATA)>
<!ATTLIST personasCitadas nombre IDREFS #REQUIRED> <!-- Uso de IDREFS-->
<!ELEMENT juzgado (#PCDATA)>
<!ENTITY lugarSucede "Juzgado Penal"> <!-- Enitdad general interna-->

=== Alexcr0103/EjerciciosLMSGI2023-24/Practicas/examen1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juicio SYSTEM "examen1.dtd">
<juicio>
    <abogado nombre="Harvey Specter" defiende="Martin Smith" acusa="DanielHardman"/>
    <abogado nombre="Mike Ross" defiende="Rick Hoffman" acusa="TravisTanner"/>
    <abogado nombre="Donna Paulsen" acusa="HenryGerard" especialidad="civil"/>
    <delitos tipo="robo" acusado="DanielHardman">
        <multa>15.000 dolares</multa>
        <antedecentes>Si</antedecentes>
   </delitos>
   <delitos tipo="atraco" acusado="TravisTanner">
        <carcel nombre="Texas">15 a√±os</carcel>
   </delitos>
   <lugar>
        <ciudad nombre="Chicago"/>
        <personasCitadas nombre="DanielHardman TravisTanner"/>
        <juzgado> &lugarSucede; </juzgado>
   </lugar>
</juicio>
